# Generated by Django 3.2.18 on 2023-05-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0004_auto_20230513_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='progress',
        ),
    ]
