# Generated by Django 3.2.18 on 2023-05-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0005_remove_savings_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='saving_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetracker.savings'),
        ),
    ]
