# Generated by Django 3.2.18 on 2023-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0006_transaction_saving_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
